#!/bin/sh

# Install ansible aur library
git clone https://github.com/kewlfft/ansible-aur.git ~/.ansible/plugins/modules/aur

# Install ansible
sudo pacman --noconfirm -S ansible

# Execute base install
ansible-playbook ~/deployment/base-install.yml

if [ "$HOSTNAME" = "Cellaris" ]
then
	ansible-playbook ~/deployment/home-install.yml
elif [ "$HOSTNAME" = "Mobilus" ]
then
	ansible-playbook ~/deployment/notebook-install.yml
elif [ "$HOSTNAME" = "workarch" ]
then
	ansible-playbook ~/deployment/work-install.yml
fi
