#! /bin/sh

bspc monitor DVI-D-1 -d 1 2
bspc monitor VGA-1 -d 3 4 5

bspc config border_width         1
bspc config window_gap          5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config ignore_ewmh_focus true

bspc rule -a mplayer2 state=floating
bspc rule -a Emacs state=tiled
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Brave-browser desktop=^1
bspc rule -a kitty desktop=^1
bspc rule -a discord state=tiled desktop=^3
bspc rule -a Riot desktop=^3
bspc rule -a Slack desktop=^3
bspc rule -a "Toggl Desktop" desktop=^3
bspc rule -a Thunderbird desktop=^3
bspc rule -a plexmediaplayer desktop=^2
bspc rule -a Steam desktop=^2
bspc rule -a Lutris desktop=^2
bspc rule -a "Wine" state=tiled desktop=^2
bspc rule -a Zathura state=tiled desktop=^4
bspc rule -a okular desktop=^4
