#! /bin/bash

if [[ $(hostname) == 'Cellaris' ]]; then
	bspc monitor DVI-D-0 -d 1
	bspc monitor DP-4 -d 2
	bspc rule -a Brave-browser desktop=^1
	bspc rule -a kitty desktop=^1
	bspc rule -a discord state=tiled desktop=^2
	bspc rule -a Element desktop=^2
	bspc rule -a Slack desktop=^2
	bspc rule -a "Toggl Desktop" desktop=^2
	bspc rule -a Thunderbird desktop=^2
	bspc rule -a korganizer desktop=^2
	bspc rule -a plexmediaplayer desktop=^1
	bspc rule -a Plexamp desktop=^2 state=tiled # rectangle=300x1024+1620+-1
	bspc rule -a jellyamp desktop=^2 state=tiled
	bspc rule -a Emacs state=tiled desktop=^1
	bspc rule -a Steam desktop=^1
	bspc rule -a Lutris desktop=^1
	bspc rule -a "Wine" state=tiled desktop=^1
	bspc rule -a Zathura state=tiled desktop=^2
	bspc rule -a okular desktop=^2
elif [[ $(hostname) == 'workarch' ]]; then
	bspc monitor eDP-1 -d 1 10
	bspc rule -a Brave-browser desktop=^1
	bspc rule -a kitty desktop=^1
	bspc rule -a discord state=tiled desktop=^1
	bspc rule -a Element desktop=^1
	bspc rule -a Slack desktop=^1
	bspc rule -a "Toggl Desktop" desktop=^1
	bspc rule -a Thunderbird desktop=^1
	bspc rule -a korganizer desktop=^1
	bspc rule -a plexmediaplayer desktop=^1
	bspc rule -a Plexamp desktop=^1 state=tiled # rectangle=300x1024+1620+-1
	bspc rule -a jellyamp desktop=^1 state=tiled
	bspc rule -a Emacs state=tiled desktop=^1
	bspc rule -a Steam desktop=^1
	bspc rule -a Lutris desktop=^1
	bspc rule -a "Wine" state=tiled desktop=^1
	bspc rule -a Zathura state=tiled desktop=^1
	bspc rule -a okular desktop=^1
fi

bspc rule -a zoom state=tiled layer=normal
bspc rule -a pavucontrol-qt state=tiled
bspc rule -a Screenkey manage=off

bspc config pointer_follows_monitor true

bspc config border_width         1
bspc config window_gap          5
bspc desktop --layout monocle


# bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config ignore_ewmh_focus true
wmname LG3D



kitty &
sudo xkeysnail --watch ~/.config/xkeysnail/config.py 2>&1 | tee /tmp/xkeysnail.log
